### ISSUE TITLE
BLOCK: Pagination block needs better styles 

### ISSUE THREAD

**Issue by knice** [ucsc/theme-ucsc#14]
Pagination is compact and small. [We need to improve this](https://agentestudio.com/blog/pagination-design-examples-and-best-practices).

![screenshot-2022-03-23-122609](https://user-images.githubusercontent.com/36719/159780151-b19d7f3c-3fe5-4e27-92f6-f952b67f5a4f.jpg)

**Comment by Herm71** [comment]
styled.
