### ISSUE TITLE
Setup UCSC custom blocks plugin on CP "sandbox" site

### ISSUE THREAD

**Issue by knice** [ucsc/theme-ucsc#52]
The UCSC custom blocks plugin requires a little bit of setup to work properly. Someone needs to setup the config on the [Sandbox site in CampusPress](https://sandbox.wordpress.ucsc.edu/).

**Comment by Herm71** [comment]
The UCSC Custom Blocks Plugin has been set up on the Sandbox site. Kumar is still working on refactoring, so he has not yet incorporated our latest edits; however, he intends to update by the end of the week.
